### ISSUE TITLE
eups declare -r . -c failure

### ISSUE THREAD

**Issue by rhiannonlynne** [RobertLuptonTheGood/eups#45] opened 2015-07-01 23:13 UTC
sims_maf_contrib is a github repo we encourage people to use for general (non-LSST) contributions to sims_maf. 
as such, it's git cloned and then usually put into something like ~/lsstRepos/sims_maf_contrib
(vs. ~/lsst/ .. etc for LSST's eups distributed packages). 

After it's cloned, doing :
cd ~/lsstRepos/sims_maf_contrib
eups declare -r . -c 
results in a nonsense path being stored in eups. 
Example:
[lucy:~/lsstRepos/sims_maf_contrib] lynnej% pwd
/Users/lynnej/lsstRepos/sims_maf_contrib
[lucy:~/lsstRepos/sims_maf_contrib] lynnej% eups list sims_maf_contrib
eups list: Unable to find product sims_maf_contrib
[lucy:~/lsstRepos/sims_maf_contrib] lynnej% eups declare -r . -c
[lucy:~/lsstRepos/sims_maf_contrib] lynnej% setup sims_maf_contrib
setup: Table file not found for sims_maf_contrib tag:current (DarwinX86): /Users/lynnej/lsst/epos/sims_maf_contrib/ups/sims_maf_contrib.table
** (note the garbled path above - the directory is not lsst/epos/ but rather lsstRepos )

What does seem to work is using the tag '$USER':
[lucy:~/lsstRepos/sims_maf_contrib] lynnej% eups undeclare sims_maf_contrib
[lucy:~/lsstRepos/sims_maf_contrib] lynnej% eups declare -r . -t $USER
Warning: path /Users/lynnej/lsstRepos/sims_maf_contrib is absolute, not relative to EUPS_PATH
[lucy:~/lsstRepos/sims_maf_contrib] lynnej% setup sims_maf_contrib -t $USER -t sims
[lucy:~/lsstRepos/sims_maf_contrib] lynnej%

Is this a bug? Or is this a feature, meaning that you can't use the tag current for packages outside the root EUPS directory?

**Comment by ktlim** [comment] 2015-07-02 01:45
Do you by any chance have a directory named "/Users/lynnej/lsst", and is that in your `EUPS_PATH`? I think there's a bug [here](https://github.com/RobertLuptonTheGood/eups/blob/master/python/eups/Eups.py#L2378).

**Comment by rhiannonlynne** [comment] 2015-07-02 06:35
I do have that directory in my eups_path. I think it's actually pretty common for people to put the lsst stack in their home directory, in a directory named lsst, and then use lsstRepos for the gith cloned versions of packages.

**Comment by ctslater** [comment] 2015-09-25 22:05
I'm also running into eups declare mangling paths. In my case my $EUPS_PATH is /Users/ctslater/lsst, and I want to declare packages that live in /Users/ctslater/lsst_dev/pkgname. I think the line that KT linked to is indeed responsible, as it ends up declaring my packages as /Users/ctslater/lsst/dev/pkgname. 

The problem is that `os.path.commonprefix()` is misleading and does a letter-by-letter comparison. There's a new function `commonpath()` implemented in python 3.5 that does the right thing, see http://bugs.python.org/issue10395. I suspect the best way to fix this is to copy the `commonpath()` implementation from that patch into eups and use that instead of `commonprefix()`

**Comment by RobertLuptonTheGood** [comment] 2015-11-17 16:15
Fixed as suggested and pushed to master.  

Actually I fixed it a while ago, but didn't push the change.  Mea Culpa

**Comment by mjuric** [comment] 2016-01-04 09:48
Fixed by 2d484e3638a5a4d6065a1f42f38689e247ff8ae6.

**Closed by mjuric** 2016-01-04 09:48 UTC
